Adding example for cloud-events
edgexfoundry-holding/app-service-examples pull request #22
Opened 2020-03-30 23:40 UTC by adam-intel

2020-04-07 17:00 UTC, jim-wang-yutsung requested changes
Some suggestions to change...

2020-04-07 17:00 UTC, jim-wang-yutsung commented on app-services/cloud-event-transforms/README.md
> +You can trigger this this pipeline by using the http trigger using a tool like postman and sending an edgex event.
```suggestion
You can trigger this pipeline by using the http trigger from a tool like postman and sending an edgex event in the JSON body as payload. 
```

2020-04-07 17:00 UTC, jim-wang-yutsung commented on app-services/cloud-event-transforms/main.go
> +		edgexcontext.LoggingClient.Error(fmt.Sprintf("failed to create client, %v", err))
Shouldn't we return false here?

2020-04-07 17:00 UTC, jim-wang-yutsung commented on app-services/cloud-event-transforms/main.go
> +			edgexcontext.LoggingClient.Error(fmt.Sprintf("failed to send: %v", err))
return false for this error case?

2020-04-07 17:00 UTC, jim-wang-intel commented on app-services/cloud-event-transforms/pkg/transforms/conversion.go
> +	if result, ok := params[0].([]cloudevents.Event); ok {
do the opposite to return error earlier if cast is NOT ok so that the whole code logic needs not indent.

2020-04-07 20:18 UTC, adam-intel commented on app-services/cloud-event-transforms/main.go
> +		edgexcontext.LoggingClient.Error(fmt.Sprintf("failed to create client, %v", err))
Yes I'll add that

2020-04-07 20:18 UTC, adam-intel commented on app-services/cloud-event-transforms/main.go
> +			edgexcontext.LoggingClient.Error(fmt.Sprintf("failed to send: %v", err))
Yes I'll add that

2020-04-07 21:02 UTC, jim-wang-yutsung approved these changes
LGTM

2020-04-08 01:36 UTC, rsdmike approved these changes

2020-04-08 01:36 UTC, merged